import { Card } from '../types.js';

export const DEMONESS_CARDS: Card[] = [
  // ─── 1-Cost ────────────────────────────────────────────────────────────
  {
    id: 'dm-whisper-seeker',
    name: 'Whisper Seeker',
    cost: 1,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'demoness',
    description: 'Corruption',
    attack: 1,
    health: 1,
    keywords: ['corruption'],
  },
  {
    id: 'dm-poisoned-blade',
    name: 'Poisoned Blade',
    cost: 1,
    type: 'sealed-artifact',
    rarity: 'common',
    pathway: 'demoness',
    description: '',
    attack: 1,
    durability: 3,
  },
  {
    id: 'dm-shadow-apprentice',
    name: 'Shadow Apprentice',
    cost: 1,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'demoness',
    description: 'Stealth',
    attack: 1,
    health: 1,
    keywords: ['stealth'],
  },
  {
    id: 'dm-toxic-drip',
    name: 'Toxic Drip',
    cost: 1,
    type: 'ritual',
    rarity: 'common',
    pathway: 'demoness',
    description: 'Deal 2 damage to a minion.',
    effect: { type: 'damage', value: 2, target: 'enemy' },
  },

  // ─── 2-Cost ────────────────────────────────────────────────────────────
  {
    id: 'dm-seductress',
    name: 'Seductress',
    cost: 2,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'demoness',
    description: '',
    attack: 3,
    health: 2,
  },
  {
    id: 'dm-venom-touch',
    name: 'Venom Touch',
    cost: 2,
    type: 'ritual',
    rarity: 'common',
    pathway: 'demoness',
    description: 'Deal 2 damage to a minion. If it dies, draw a card.',
    effect: { type: 'damage', value: 2, target: 'enemy' },
  },
  {
    id: 'dm-spider-initiate',
    name: 'Spider Initiate',
    cost: 2,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'demoness',
    description: 'Corruption',
    attack: 1,
    health: 3,
    keywords: ['corruption'],
  },
  {
    id: 'dm-hex-curse',
    name: 'Hex Curse',
    cost: 2,
    type: 'ritual',
    rarity: 'rare',
    pathway: 'demoness',
    description: 'Give an enemy minion -2 Attack.',
    effect: { type: 'debuff', target: 'enemy', buffAttack: -2, buffHealth: 0 },
  },

  // ─── 3-Cost ────────────────────────────────────────────────────────────
  {
    id: 'dm-night-assassin',
    name: 'Night Assassin',
    cost: 3,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'demoness',
    description: 'Stealth. Corruption.',
    attack: 2,
    health: 2,
    keywords: ['stealth', 'corruption'],
  },
  {
    id: 'dm-corrosive-fog',
    name: 'Corrosive Fog',
    cost: 3,
    type: 'ritual',
    rarity: 'common',
    pathway: 'demoness',
    description: 'Deal 1 damage to all enemy minions.',
    effect: { type: 'damage', value: 1, target: 'all-enemies' },
  },
  {
    id: 'dm-envenom-blade',
    name: 'Envenom Blade',
    cost: 3,
    type: 'sealed-artifact',
    rarity: 'rare',
    pathway: 'demoness',
    description: '',
    attack: 3,
    durability: 2,
  },
  {
    id: 'dm-web-weaver',
    name: 'Web Weaver',
    cost: 3,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'demoness',
    description: 'Corruption',
    attack: 2,
    health: 3,
    keywords: ['corruption'],
  },

  // ─── 4-Cost ────────────────────────────────────────────────────────────
  {
    id: 'dm-desire-apostle',
    name: 'Desire Apostle',
    cost: 4,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'demoness',
    description: 'Frenzy. Corruption.',
    attack: 3,
    health: 3,
    keywords: ['frenzy', 'corruption'],
  },
  {
    id: 'dm-catastrophe-dagger',
    name: 'Catastrophe Dagger',
    cost: 4,
    type: 'sealed-artifact',
    rarity: 'epic',
    pathway: 'demoness',
    description: '',
    attack: 4,
    durability: 2,
  },
  {
    id: 'dm-plague-spreader',
    name: 'Plague Spreader',
    cost: 4,
    type: 'ritual',
    rarity: 'rare',
    pathway: 'demoness',
    description: 'Deal 2 damage to all enemy minions.',
    effect: { type: 'damage', value: 2, target: 'all-enemies' },
  },
  {
    id: 'dm-nightmare-weaver',
    name: 'Nightmare Weaver',
    cost: 4,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'demoness',
    description: 'Stealth',
    attack: 4,
    health: 3,
    keywords: ['stealth'],
  },

  // ─── 5-Cost ────────────────────────────────────────────────────────────
  {
    id: 'dm-witch-of-despair',
    name: 'Witch of Despair',
    cost: 5,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'demoness',
    description: 'Corruption. Provoke.',
    attack: 3,
    health: 5,
    keywords: ['corruption', 'provoke'],
  },
  {
    id: 'dm-plague-of-sin',
    name: 'Plague of Sin',
    cost: 5,
    type: 'ritual',
    rarity: 'epic',
    pathway: 'demoness',
    description: 'Destroy a minion with 4 or less Attack.',
    effect: { type: 'destroy', target: 'enemy' },
  },
  {
    id: 'dm-shadow-assassin',
    name: 'Shadow Assassin',
    cost: 5,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'demoness',
    description: 'Stealth. Corruption. Frenzy.',
    attack: 4,
    health: 3,
    keywords: ['stealth', 'corruption', 'frenzy'],
  },

  // ─── 6-Cost ────────────────────────────────────────────────────────────
  {
    id: 'dm-abyss-temptress',
    name: 'Abyss Temptress',
    cost: 6,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'demoness',
    description: 'Stealth. Corruption. Frenzy.',
    attack: 5,
    health: 4,
    keywords: ['stealth', 'corruption', 'frenzy'],
  },
  {
    id: 'dm-soul-harvest',
    name: 'Soul Harvest',
    cost: 6,
    type: 'ritual',
    rarity: 'epic',
    pathway: 'demoness',
    description: 'Destroy all minions with 3 or less Attack.',
    effect: { type: 'destroy', target: 'all' },
  },

  // ─── 7-Cost ────────────────────────────────────────────────────────────
  {
    id: 'dm-sin-cardinal',
    name: 'Sin Cardinal',
    cost: 7,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'demoness',
    description: 'Haste. Corruption.',
    attack: 6,
    health: 5,
    keywords: ['haste', 'corruption'],
  },

  // ─── 8+ Cost ───────────────────────────────────────────────────────────
  {
    id: 'dm-mother-of-depravity',
    name: 'Mother of Depravity',
    cost: 8,
    type: 'beyonder',
    rarity: 'legendary',
    pathway: 'demoness',
    description: 'Haste. Corruption. Destroy a random enemy minion when played.',
    attack: 6,
    health: 6,
    keywords: ['haste', 'corruption'],
    battlecry: { type: 'destroy', value: 0, target: 'random-enemy' },
    flavorText: 'Desire consumes all who gaze upon her.',
  },
  {
    id: 'dm-primordial-demoness',
    name: 'Primordial Demoness',
    cost: 10,
    type: 'beyonder',
    rarity: 'legendary',
    pathway: 'demoness',
    description: 'Haste. Corruption. Stealth. Destroy all enemy minions with 4 or less Health.',
    attack: 7,
    health: 7,
    keywords: ['haste', 'corruption', 'stealth'],
    flavorText: 'Born of the original sin, she is corruption incarnate.',
  },

  // ─── Mystical Items ────────────────────────────────────────────────────
  {
    id: 'dm-poison-trap',
    name: 'Poison Trap',
    cost: 2,
    type: 'mystical-item',
    rarity: 'rare',
    pathway: 'demoness',
    description: 'When enemy plays a minion, give it -2 Attack.',
    trigger: 'on-minion-played',
    effect: { type: 'debuff', target: 'random-enemy', buffAttack: -2, buffHealth: 0 },
  },
  {
    id: 'dm-death-wish',
    name: 'Death Wish',
    cost: 3,
    type: 'mystical-item',
    rarity: 'epic',
    pathway: 'demoness',
    description: 'When a minion dies, deal 2 damage to the enemy hero.',
    trigger: 'on-minion-death',
    effect: { type: 'damage', value: 2, target: 'enemy-hero' },
  },
];
