import { Card } from '../types.js';

export const DOOR_CARDS: Card[] = [
  // ─── 1-Cost ────────────────────────────────────────────────────────────
  {
    id: 'd-planar-scout',
    name: 'Planar Scout',
    cost: 1,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'door',
    description: '',
    attack: 1,
    health: 2,
  },
  {
    id: 'd-spatial-tear',
    name: 'Spatial Tear',
    cost: 1,
    type: 'ritual',
    rarity: 'common',
    pathway: 'door',
    description: 'Deal 1 damage. Draw 1 card.',
    effect: { type: 'damage', value: 1, target: 'any' },
  },
  {
    id: 'd-blink-initiate',
    name: 'Blink Initiate',
    cost: 1,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'door',
    description: 'Frenzy',
    attack: 1,
    health: 1,
    keywords: ['frenzy'],
  },
  {
    id: 'd-phase-shift',
    name: 'Phase Shift',
    cost: 1,
    type: 'ritual',
    rarity: 'common',
    pathway: 'door',
    description: 'Draw 1 card.',
    effect: { type: 'draw', value: 1, target: 'none' },
  },

  // ─── 2-Cost ────────────────────────────────────────────────────────────
  {
    id: 'd-wandering-thief',
    name: 'Wandering Thief',
    cost: 2,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'door',
    description: 'Stealth',
    attack: 2,
    health: 2,
    keywords: ['stealth'],
  },
  {
    id: 'd-dimension-hopper',
    name: 'Dimension Hopper',
    cost: 2,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'door',
    description: 'Frenzy',
    attack: 3,
    health: 2,
    keywords: ['frenzy'],
  },
  {
    id: 'd-rift-blade',
    name: 'Rift Blade',
    cost: 2,
    type: 'sealed-artifact',
    rarity: 'common',
    pathway: 'door',
    description: '',
    attack: 2,
    durability: 2,
  },
  {
    id: 'd-spatial-siphon',
    name: 'Spatial Siphon',
    cost: 2,
    type: 'ritual',
    rarity: 'common',
    pathway: 'door',
    description: 'Deal 2 damage. Draw 1 card.',
    effect: { type: 'damage', value: 2, target: 'any' },
  },

  // ─── 3-Cost ────────────────────────────────────────────────────────────
  {
    id: 'd-teleportation-strike',
    name: 'Teleportation Strike',
    cost: 3,
    type: 'ritual',
    rarity: 'common',
    pathway: 'door',
    description: 'Deal 3 damage to a minion. Draw 1 card.',
    effect: { type: 'damage', value: 3, target: 'enemy' },
  },
  {
    id: 'd-portal-keeper',
    name: 'Portal Keeper',
    cost: 3,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'door',
    description: 'Provoke',
    attack: 2,
    health: 5,
    keywords: ['provoke'],
  },
  {
    id: 'd-planar-raider',
    name: 'Planar Raider',
    cost: 3,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'door',
    description: 'Stealth. Frenzy.',
    attack: 3,
    health: 2,
    keywords: ['stealth', 'frenzy'],
  },
  {
    id: 'd-dimension-lock',
    name: 'Dimension Lock',
    cost: 3,
    type: 'ritual',
    rarity: 'rare',
    pathway: 'door',
    description: 'Return an enemy minion to their hand.',
    effect: { type: 'return', target: 'enemy' },
  },

  // ─── 4-Cost ────────────────────────────────────────────────────────────
  {
    id: 'd-space-distortion',
    name: 'Space Distortion',
    cost: 4,
    type: 'ritual',
    rarity: 'rare',
    pathway: 'door',
    description: 'Return 2 enemy minions to their hand.',
    effect: { type: 'return', target: 'enemy' },
  },
  {
    id: 'd-plane-devourer',
    name: 'Plane Devourer',
    cost: 4,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'door',
    description: '',
    attack: 4,
    health: 5,
  },
  {
    id: 'd-void-dagger',
    name: 'Void Dagger',
    cost: 4,
    type: 'sealed-artifact',
    rarity: 'epic',
    pathway: 'door',
    description: '',
    attack: 4,
    durability: 2,
  },
  {
    id: 'd-rift-guardian',
    name: 'Rift Guardian',
    cost: 4,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'door',
    description: 'Provoke. Divination.',
    attack: 3,
    health: 4,
    keywords: ['provoke', 'divination'],
  },

  // ─── 5-Cost ────────────────────────────────────────────────────────────
  {
    id: 'd-dimensional-exile',
    name: 'Dimensional Exile',
    cost: 5,
    type: 'ritual',
    rarity: 'epic',
    pathway: 'door',
    description: 'Destroy a minion.',
    effect: { type: 'destroy', target: 'enemy' },
  },
  {
    id: 'd-void-ambassador',
    name: 'Void Ambassador',
    cost: 5,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'door',
    description: 'Stealth. Frenzy.',
    attack: 5,
    health: 4,
    keywords: ['stealth', 'frenzy'],
  },
  {
    id: 'd-mass-teleport',
    name: 'Mass Teleport',
    cost: 5,
    type: 'ritual',
    rarity: 'rare',
    pathway: 'door',
    description: 'Draw 3 cards.',
    effect: { type: 'draw', value: 3, target: 'none' },
  },

  // ─── 6-Cost ────────────────────────────────────────────────────────────
  {
    id: 'd-space-lord',
    name: 'Space Lord',
    cost: 6,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'door',
    description: 'Haste. Stealth.',
    attack: 5,
    health: 5,
    keywords: ['haste', 'stealth'],
  },

  // ─── 7-Cost ────────────────────────────────────────────────────────────
  {
    id: 'd-reality-ripper',
    name: 'Reality Ripper',
    cost: 7,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'door',
    description: 'Haste. Return a random enemy minion to their hand.',
    attack: 6,
    health: 5,
    keywords: ['haste'],
  },

  // ─── 8+ Cost ───────────────────────────────────────────────────────────
  {
    id: 'd-key-of-stars-cattleya',
    name: 'Key of Stars (Cattleya)',
    cost: 8,
    type: 'beyonder',
    rarity: 'legendary',
    pathway: 'door',
    description: 'Haste. Destroy a random enemy minion. Draw 2 cards.',
    attack: 6,
    health: 7,
    keywords: ['haste'],
    flavorText: 'She opens doors between worlds with a thought.',
  },
  {
    id: 'd-spatial-collapse',
    name: 'Spatial Collapse',
    cost: 9,
    type: 'ritual',
    rarity: 'legendary',
    pathway: 'door',
    description: 'Destroy all enemy minions. Draw 3 cards.',
    effect: { type: 'destroy', target: 'all-enemies' },
    flavorText: 'Space folds in on itself, erasing all within.',
  },

  // ─── Mystical Items ────────────────────────────────────────────────────
  {
    id: 'd-dimensional-trap',
    name: 'Dimensional Trap',
    cost: 2,
    type: 'mystical-item',
    rarity: 'rare',
    pathway: 'door',
    description: 'When enemy plays a minion, return it to their hand.',
    trigger: 'on-minion-played',
    effect: { type: 'return', target: 'enemy' },
  },
  {
    id: 'd-void-anchor',
    name: 'Void Anchor',
    cost: 3,
    type: 'mystical-item',
    rarity: 'epic',
    pathway: 'door',
    description: 'When enemy casts a spell, draw 2 cards.',
    trigger: 'on-spell-cast',
    effect: { type: 'draw', value: 2, target: 'none' },
  },
];
