import { Card } from '../types.js';

export const FOOL_CARDS: Card[] = [
  // ─── 1-Cost ────────────────────────────────────────────────────────────
  {
    id: 'f-gray-fog-wisp',
    name: 'Gray Fog Wisp',
    cost: 1,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'fool',
    description: 'Stealth',
    attack: 1,
    health: 1,
    keywords: ['stealth'],
  },
  {
    id: 'f-faceless-initiate',
    name: 'Faceless Initiate',
    cost: 1,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'fool',
    description: '',
    attack: 2,
    health: 1,
  },
  {
    id: 'f-divination-candle',
    name: 'Divination Candle',
    cost: 1,
    type: 'ritual',
    rarity: 'common',
    pathway: 'fool',
    description: 'Draw 1 card. If you have a Stealth minion, draw 2 instead.',
    effect: { type: 'draw', value: 1, target: 'none' },
  },

  // ─── 2-Cost ────────────────────────────────────────────────────────────
  {
    id: 'f-paper-figurine',
    name: 'Paper Figurine',
    cost: 2,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'fool',
    description: 'Stealth',
    attack: 2,
    health: 2,
    keywords: ['stealth'],
  },
  {
    id: 'f-spirit-medium',
    name: 'Spirit Medium',
    cost: 2,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'fool',
    description: '',
    attack: 2,
    health: 3,
  },
  {
    id: 'f-clown-performer',
    name: 'Clown Performer',
    cost: 2,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'fool',
    description: 'Divination',
    attack: 1,
    health: 3,
    keywords: ['divination'],
  },
  {
    id: 'f-fog-of-confusion',
    name: 'Fog of Confusion',
    cost: 2,
    type: 'ritual',
    rarity: 'common',
    pathway: 'fool',
    description: 'Give a friendly minion Stealth.',
    effect: { type: 'buff', target: 'friendly', buffAttack: 0, buffHealth: 0 },
  },

  // ─── 3-Cost ────────────────────────────────────────────────────────────
  {
    id: 'f-nimble-swindler',
    name: 'Nimble Swindler',
    cost: 3,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'fool',
    description: 'Stealth. Frenzy.',
    attack: 3,
    health: 2,
    keywords: ['stealth', 'frenzy'],
  },
  {
    id: 'f-marionettist',
    name: 'Marionettist',
    cost: 3,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'fool',
    description: 'Summon a 1/1 Marionette with Stealth.',
    attack: 2,
    health: 3,
    flavorText: 'Puppets dance at the whim of their master.',
  },
  {
    id: 'f-grafting-ritual',
    name: 'Grafting Ritual',
    cost: 3,
    type: 'ritual',
    rarity: 'rare',
    pathway: 'fool',
    description: 'Give a friendly minion +2/+2.',
    effect: { type: 'buff', target: 'friendly', buffAttack: 2, buffHealth: 2 },
  },

  // ─── 4-Cost ────────────────────────────────────────────────────────────
  {
    id: 'f-dream-walker',
    name: 'Dream Walker',
    cost: 4,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'fool',
    description: 'Stealth. At end of turn, gain +1/+1.',
    attack: 3,
    health: 3,
    keywords: ['stealth'],
  },
  {
    id: 'f-historian-of-lies',
    name: 'Historian of Lies',
    cost: 4,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'fool',
    description: 'Stealth. Corruption.',
    attack: 3,
    health: 2,
    keywords: ['stealth', 'corruption'],
  },
  {
    id: 'f-diversion-technique',
    name: 'Diversion Technique',
    cost: 4,
    type: 'ritual',
    rarity: 'rare',
    pathway: 'fool',
    description: 'Return an enemy minion to their hand.',
    effect: { type: 'return', target: 'enemy' },
  },

  // ─── 5-Cost ────────────────────────────────────────────────────────────
  {
    id: 'f-miracle-invoker',
    name: 'Miracle Invoker',
    cost: 5,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'fool',
    description: 'Stealth. Summon two 1/1 Marionettes with Stealth.',
    attack: 4,
    health: 4,
    keywords: ['stealth'],
  },
  {
    id: 'f-mental-plague',
    name: 'Mental Plague',
    cost: 5,
    type: 'ritual',
    rarity: 'epic',
    pathway: 'fool',
    description: 'Deal 2 damage to all enemy minions.',
    effect: { type: 'damage', value: 2, target: 'all-enemies' },
  },

  // ─── 6-Cost ────────────────────────────────────────────────────────────
  {
    id: 'f-attendant-of-mysteries',
    name: 'Attendant of Mysteries',
    cost: 6,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'fool',
    description: 'Provoke. Divination. Stealth.',
    attack: 4,
    health: 6,
    keywords: ['provoke', 'divination', 'stealth'],
    flavorText: 'Loyal to the one above the gray fog.',
  },
  {
    id: 'f-domain-of-concealment',
    name: 'Domain of Concealment',
    cost: 6,
    type: 'ritual',
    rarity: 'epic',
    pathway: 'fool',
    description: 'Give all friendly minions Stealth. Draw 2 cards.',
    effect: { type: 'draw', value: 2, target: 'none' },
  },

  // ─── 7-Cost ────────────────────────────────────────────────────────────
  {
    id: 'f-wraith-sovereign',
    name: 'Wraith Sovereign',
    cost: 7,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'fool',
    description: 'Stealth. Haste.',
    attack: 6,
    health: 5,
    keywords: ['stealth', 'haste'],
    flavorText: 'Neither living nor dead, beyond both realms.',
  },

  // ─── 8-Cost ────────────────────────────────────────────────────────────
  {
    id: 'f-bizarro-sorcerer',
    name: 'Bizarro Sorcerer',
    cost: 8,
    type: 'beyonder',
    rarity: 'legendary',
    pathway: 'fool',
    description: 'Haste. Summon two 3/3 Marionettes with Stealth.',
    attack: 6,
    health: 6,
    keywords: ['haste'],
    flavorText: 'The world is but a grand performance.',
  },

  // ─── 9-Cost ────────────────────────────────────────────────────────────
  {
    id: 'f-the-world-gehrman',
    name: 'The World (Gehrman Sparrow)',
    cost: 9,
    type: 'beyonder',
    rarity: 'legendary',
    pathway: 'fool',
    description: 'Haste. Stealth. Destroy a random enemy minion when played.',
    attack: 7,
    health: 7,
    keywords: ['haste', 'stealth'],
    battlecry: { type: 'destroy', value: 0, target: 'random-enemy' },
    flavorText: 'Gehrman Sparrow. Crazy adventurer. The World.',
  },

  // ─── 10-Cost ───────────────────────────────────────────────────────────
  {
    id: 'f-lord-of-mysteries',
    name: 'The Fool (Lord of the Mysteries)',
    cost: 10,
    type: 'beyonder',
    rarity: 'legendary',
    pathway: 'fool',
    description: 'Haste. Destroy all enemy minions. Summon three 3/3 Marionettes.',
    attack: 8,
    health: 8,
    keywords: ['haste'],
    flavorText: 'The Fool that does not belong to this era.',
  },

  // ─── Sealed Artifacts ──────────────────────────────────────────────────
  {
    id: 'f-creeping-hunger',
    name: 'Creeping Hunger',
    cost: 3,
    type: 'sealed-artifact',
    rarity: 'epic',
    pathway: 'fool',
    description: 'Madness 1: deal 1 damage to your hero at end of turn.',
    attack: 3,
    durability: 3,
  },
  {
    id: 'f-murmuring-thorn',
    name: 'Murmuring Thorn',
    cost: 2,
    type: 'sealed-artifact',
    rarity: 'rare',
    pathway: 'fool',
    description: '',
    attack: 2,
    durability: 2,
  },

  // ─── Mystical Items (Secrets) ──────────────────────────────────────────
  {
    id: 'f-gray-fog-barrier',
    name: 'Gray Fog Barrier',
    cost: 2,
    type: 'mystical-item',
    rarity: 'rare',
    pathway: 'fool',
    description: 'When your hero is attacked, negate the damage and gain Stealth on all minions.',
    trigger: 'on-hero-attacked',
    effect: { type: 'buff', target: 'all-friendlies', buffAttack: 0, buffHealth: 0 },
  },
  {
    id: 'f-trap-of-deceit',
    name: 'Trap of Deceit',
    cost: 3,
    type: 'mystical-item',
    rarity: 'epic',
    pathway: 'fool',
    description: 'When your opponent plays a minion, return it to their hand.',
    trigger: 'on-minion-played',
    effect: { type: 'return', target: 'enemy' },
  },
];
