import { Card } from '../types.js';

export const NEUTRAL_CARDS: Card[] = [
  // ─── 1-Cost ────────────────────────────────────────────────────────────
  {
    id: 'n-street-urchin',
    name: 'Street Urchin',
    cost: 1,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'neutral',
    description: '',
    attack: 1,
    health: 2,
  },
  {
    id: 'n-dock-worker',
    name: 'Dock Worker',
    cost: 1,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'neutral',
    description: '',
    attack: 2,
    health: 1,
  },
  {
    id: 'n-newspaper-boy',
    name: 'Newspaper Boy',
    cost: 1,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'neutral',
    description: 'Frenzy',
    attack: 1,
    health: 1,
    keywords: ['frenzy'],
  },

  // ─── 2-Cost ────────────────────────────────────────────────────────────
  {
    id: 'n-church-guard',
    name: 'Church Guard',
    cost: 2,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'neutral',
    description: 'Provoke',
    attack: 1,
    health: 3,
    keywords: ['provoke'],
  },
  {
    id: 'n-tingen-scholar',
    name: 'Tingen Scholar',
    cost: 2,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'neutral',
    description: '',
    attack: 2,
    health: 3,
  },
  {
    id: 'n-steam-mechanic',
    name: 'Steam Mechanic',
    cost: 2,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'neutral',
    description: '',
    attack: 3,
    health: 2,
  },
  {
    id: 'n-fortune-teller',
    name: 'Fortune Teller',
    cost: 2,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'neutral',
    description: 'Divination',
    attack: 2,
    health: 2,
    keywords: ['divination'],
  },

  // ─── 3-Cost ────────────────────────────────────────────────────────────
  {
    id: 'n-midnight-poet',
    name: 'Midnight Poet',
    cost: 3,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'neutral',
    description: '',
    attack: 3,
    health: 3,
  },
  {
    id: 'n-backlund-detective',
    name: 'Backlund Detective',
    cost: 3,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'neutral',
    description: 'Stealth',
    attack: 3,
    health: 2,
    keywords: ['stealth'],
  },
  {
    id: 'n-beyonder-hunter',
    name: 'Beyonder Hunter',
    cost: 3,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'neutral',
    description: 'Corruption',
    attack: 2,
    health: 2,
    keywords: ['corruption'],
  },

  // ─── 4-Cost ────────────────────────────────────────────────────────────
  {
    id: 'n-loen-knight',
    name: 'Loen Kingdom Knight',
    cost: 4,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'neutral',
    description: 'Provoke',
    attack: 3,
    health: 5,
    keywords: ['provoke'],
  },
  {
    id: 'n-nighthawk-enforcer',
    name: 'Nighthawk Enforcer',
    cost: 4,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'neutral',
    description: 'Frenzy',
    attack: 4,
    health: 3,
    keywords: ['frenzy'],
  },

  // ─── 5-Cost ────────────────────────────────────────────────────────────
  {
    id: 'n-punisher-of-church',
    name: 'Punisher of the Church',
    cost: 5,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'neutral',
    description: 'Provoke. Divination.',
    attack: 4,
    health: 5,
    keywords: ['provoke', 'divination'],
  },
  {
    id: 'n-iron-council-agent',
    name: 'Iron Council Agent',
    cost: 5,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'neutral',
    description: 'Haste',
    attack: 5,
    health: 4,
    keywords: ['haste'],
  },

  // ─── 6-Cost ────────────────────────────────────────────────────────────
  {
    id: 'n-high-sequence-seeker',
    name: 'High-Sequence Seeker',
    cost: 6,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'neutral',
    description: '',
    attack: 5,
    health: 6,
  },

  // ─── 7-Cost ────────────────────────────────────────────────────────────
  {
    id: 'n-sealed-artifact-guardian',
    name: 'Sealed Artifact Guardian',
    cost: 7,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'neutral',
    description: 'Provoke. Divination.',
    attack: 5,
    health: 8,
    keywords: ['provoke', 'divination'],
  },

  // ─── Rituals (Spells) ──────────────────────────────────────────────────
  {
    id: 'n-spirit-vision',
    name: 'Spirit Vision',
    cost: 1,
    type: 'ritual',
    rarity: 'common',
    pathway: 'neutral',
    description: 'Draw 1 card.',
    effect: { type: 'draw', value: 1, target: 'none' },
  },
  {
    id: 'n-crimson-moon-gaze',
    name: 'Crimson Moon Gaze',
    cost: 3,
    type: 'ritual',
    rarity: 'common',
    pathway: 'neutral',
    description: 'Deal 3 damage to a minion.',
    effect: { type: 'damage', value: 3, target: 'enemy' },
  },
  {
    id: 'n-loen-military-might',
    name: 'Loen Military Might',
    cost: 4,
    type: 'ritual',
    rarity: 'rare',
    pathway: 'neutral',
    description: 'Give a minion +3/+3.',
    effect: { type: 'buff', target: 'any', buffAttack: 3, buffHealth: 3 },
  },
  {
    id: 'n-source-quality-surge',
    name: 'Source Quality Surge',
    cost: 5,
    type: 'ritual',
    rarity: 'rare',
    pathway: 'neutral',
    description: 'Draw 3 cards.',
    effect: { type: 'draw', value: 3, target: 'none' },
  },
];
