import { Card } from '../types.js';

export const RED_PRIEST_CARDS: Card[] = [
  // ─── 1-Cost ────────────────────────────────────────────────────────────
  {
    id: 'rp-ember-acolyte',
    name: 'Ember Acolyte',
    cost: 1,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'red-priest',
    description: '',
    attack: 2,
    health: 1,
  },
  {
    id: 'rp-flame-tongue',
    name: 'Flame Tongue',
    cost: 1,
    type: 'ritual',
    rarity: 'common',
    pathway: 'red-priest',
    description: 'Deal 2 damage to a minion.',
    effect: { type: 'damage', value: 2, target: 'any' },
  },
  {
    id: 'rp-fire-spark',
    name: 'Fire Spark',
    cost: 1,
    type: 'ritual',
    rarity: 'common',
    pathway: 'red-priest',
    description: 'Deal 1 damage to the enemy hero.',
    effect: { type: 'damage', value: 1, target: 'enemy-hero' },
  },
  {
    id: 'rp-kindling-servant',
    name: 'Kindling Servant',
    cost: 1,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'red-priest',
    description: '',
    attack: 1,
    health: 2,
  },

  // ─── 2-Cost ────────────────────────────────────────────────────────────
  {
    id: 'rp-sacred-flame-bearer',
    name: 'Sacred Flame Bearer',
    cost: 2,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'red-priest',
    description: '',
    attack: 3,
    health: 2,
  },
  {
    id: 'rp-purification-zealot',
    name: 'Purification Zealot',
    cost: 2,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'red-priest',
    description: 'Frenzy',
    attack: 2,
    health: 2,
    keywords: ['frenzy'],
  },
  {
    id: 'rp-burning-oil',
    name: 'Burning Oil',
    cost: 2,
    type: 'ritual',
    rarity: 'common',
    pathway: 'red-priest',
    description: 'Deal 3 damage to a minion.',
    effect: { type: 'damage', value: 3, target: 'enemy' },
  },
  {
    id: 'rp-flame-dancer',
    name: 'Flame Dancer',
    cost: 2,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'red-priest',
    description: 'Haste',
    attack: 2,
    health: 1,
    keywords: ['haste'],
  },

  // ─── 3-Cost ────────────────────────────────────────────────────────────
  {
    id: 'rp-volcanic-eruption',
    name: 'Volcanic Eruption',
    cost: 3,
    type: 'ritual',
    rarity: 'rare',
    pathway: 'red-priest',
    description: 'Deal 2 damage to ALL characters (both heroes and all minions).',
    effect: { type: 'damage', value: 2, target: 'all-characters' },
  },
  {
    id: 'rp-inferno-priest',
    name: 'Inferno Priest',
    cost: 3,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'red-priest',
    description: 'Haste',
    attack: 3,
    health: 2,
    keywords: ['haste'],
  },
  {
    id: 'rp-blood-sacrifice',
    name: 'Blood Sacrifice',
    cost: 3,
    type: 'ritual',
    rarity: 'common',
    pathway: 'red-priest',
    description: 'Deal 4 damage to a minion.',
    effect: { type: 'damage', value: 4, target: 'any' },
  },
  {
    id: 'rp-pyre-acolyte',
    name: 'Pyre Acolyte',
    cost: 3,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'red-priest',
    description: '',
    attack: 3,
    health: 3,
  },
  {
    id: 'rp-sacrificial-blade',
    name: 'Sacrificial Blade',
    cost: 3,
    type: 'sealed-artifact',
    rarity: 'rare',
    pathway: 'red-priest',
    description: '',
    attack: 3,
    durability: 2,
  },

  // ─── 4-Cost ────────────────────────────────────────────────────────────
  {
    id: 'rp-crimson-ritualist',
    name: 'Crimson Ritualist',
    cost: 4,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'red-priest',
    description: '',
    attack: 4,
    health: 4,
  },
  {
    id: 'rp-burning-fanatic',
    name: 'Burning Fanatic',
    cost: 4,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'red-priest',
    description: 'Haste. Madness 1.',
    attack: 5,
    health: 3,
    keywords: ['haste', 'madness'],
    madnessValue: 1,
  },
  {
    id: 'rp-immolation',
    name: 'Immolation',
    cost: 4,
    type: 'ritual',
    rarity: 'rare',
    pathway: 'red-priest',
    description: 'Deal 3 damage to all minions.',
    effect: { type: 'damage', value: 3, target: 'all' },
  },
  {
    id: 'rp-conflagration-knight',
    name: 'Conflagration Knight',
    cost: 4,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'red-priest',
    description: 'Frenzy',
    attack: 4,
    health: 3,
    keywords: ['frenzy'],
  },

  // ─── 5-Cost ────────────────────────────────────────────────────────────
  {
    id: 'rp-scarlet-monarch',
    name: 'Scarlet Monarch',
    cost: 5,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'red-priest',
    description: 'Haste',
    attack: 5,
    health: 4,
    keywords: ['haste'],
  },
  {
    id: 'rp-hellfire-rain',
    name: 'Hellfire Rain',
    cost: 5,
    type: 'ritual',
    rarity: 'epic',
    pathway: 'red-priest',
    description: 'Deal 3 damage to all enemies.',
    effect: { type: 'damage', value: 3, target: 'all-enemies' },
  },
  {
    id: 'rp-zealot-commander',
    name: 'Zealot Commander',
    cost: 5,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'red-priest',
    description: 'Frenzy. Haste.',
    attack: 4,
    health: 4,
    keywords: ['frenzy', 'haste'],
  },

  // ─── 6-Cost ────────────────────────────────────────────────────────────
  {
    id: 'rp-godly-pyre',
    name: 'Godly Pyre',
    cost: 6,
    type: 'ritual',
    rarity: 'epic',
    pathway: 'red-priest',
    description: 'Deal 5 damage to all enemies.',
    effect: { type: 'damage', value: 5, target: 'all-enemies' },
  },
  {
    id: 'rp-flame-sovereign',
    name: 'Flame Sovereign',
    cost: 6,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'red-priest',
    description: 'Haste',
    attack: 6,
    health: 4,
    keywords: ['haste'],
  },

  // ─── 7-Cost ────────────────────────────────────────────────────────────
  {
    id: 'rp-calamity-incarnate',
    name: 'Calamity Incarnate',
    cost: 7,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'red-priest',
    description: 'Haste. Deal 3 damage to all enemies when played.',
    attack: 6,
    health: 5,
    keywords: ['haste'],
    battlecry: { type: 'damage', value: 3, target: 'all-enemies' },
  },

  // ─── 8-Cost ────────────────────────────────────────────────────────────
  {
    id: 'rp-primordial-flame',
    name: 'Primordial Flame',
    cost: 8,
    type: 'ritual',
    rarity: 'legendary',
    pathway: 'red-priest',
    description: 'Deal 8 damage to the enemy hero.',
    effect: { type: 'damage', value: 8, target: 'enemy-hero' },
    flavorText: 'The fire that existed before creation.',
  },

  // ─── 9-Cost ────────────────────────────────────────────────────────────
  {
    id: 'rp-red-angel-medici',
    name: 'Red Angel (Medici)',
    cost: 9,
    type: 'beyonder',
    rarity: 'legendary',
    pathway: 'red-priest',
    description: 'Haste. Deal 5 damage to the enemy hero when played.',
    attack: 7,
    health: 6,
    keywords: ['haste'],
    battlecry: { type: 'damage', value: 5, target: 'enemy-hero' },
    flavorText: 'The flames of purity consume all.',
  },

  // ─── Mystical Items ────────────────────────────────────────────────────
  {
    id: 'rp-flame-trap',
    name: 'Flame Trap',
    cost: 2,
    type: 'mystical-item',
    rarity: 'rare',
    pathway: 'red-priest',
    description: 'When an enemy plays a minion, deal 3 damage to that minion.',
    trigger: 'on-minion-played',
    effect: { type: 'damage', value: 3, target: 'random-enemy' },
  },
  {
    id: 'rp-explosive-ward',
    name: 'Explosive Ward',
    cost: 3,
    type: 'mystical-item',
    rarity: 'epic',
    pathway: 'red-priest',
    description: 'When your hero is attacked by a minion, deal 4 damage to that minion.',
    trigger: 'on-hero-attacked',
    effect: { type: 'damage', value: 4, target: 'random-enemy' },
  },
];
