import { Card } from '../types.js';

export const SUN_CARDS: Card[] = [
  // ─── 1-Cost ────────────────────────────────────────────────────────────
  {
    id: 's-dawn-acolyte',
    name: 'Dawn Acolyte',
    cost: 1,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'sun',
    description: '',
    attack: 1,
    health: 3,
  },
  {
    id: 's-holy-light',
    name: 'Holy Light',
    cost: 1,
    type: 'ritual',
    rarity: 'common',
    pathway: 'sun',
    description: 'Restore 3 Health.',
    effect: { type: 'heal', value: 3, target: 'any' },
  },
  {
    id: 's-prayer-chant',
    name: 'Prayer Chant',
    cost: 1,
    type: 'ritual',
    rarity: 'common',
    pathway: 'sun',
    description: 'Give a minion +0/+2.',
    effect: { type: 'buff', target: 'friendly', buffAttack: 0, buffHealth: 2 },
  },
  {
    id: 's-choir-boy',
    name: 'Choir Boy',
    cost: 1,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'sun',
    description: 'Divination',
    attack: 1,
    health: 1,
    keywords: ['divination'],
  },

  // ─── 2-Cost ────────────────────────────────────────────────────────────
  {
    id: 's-radiant-knight',
    name: 'Radiant Knight',
    cost: 2,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'sun',
    description: 'Divination',
    attack: 2,
    health: 2,
    keywords: ['divination'],
  },
  {
    id: 's-solar-blessing',
    name: 'Solar Blessing',
    cost: 2,
    type: 'ritual',
    rarity: 'common',
    pathway: 'sun',
    description: 'Give a minion +1/+2.',
    effect: { type: 'buff', target: 'friendly', buffAttack: 1, buffHealth: 2 },
  },
  {
    id: 's-templar-recruit',
    name: 'Templar Recruit',
    cost: 2,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'sun',
    description: 'Provoke',
    attack: 1,
    health: 4,
    keywords: ['provoke'],
  },
  {
    id: 's-dawn-shield',
    name: 'Dawn Shield',
    cost: 2,
    type: 'sealed-artifact',
    rarity: 'common',
    pathway: 'sun',
    description: '',
    attack: 1,
    durability: 4,
  },

  // ─── 3-Cost ────────────────────────────────────────────────────────────
  {
    id: 's-church-healer',
    name: 'Church Healer',
    cost: 3,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'sun',
    description: 'Restore 3 Health to your hero when played.',
    attack: 2,
    health: 4,
  },
  {
    id: 's-sunlight-guardian',
    name: 'Sunlight Guardian',
    cost: 3,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'sun',
    description: 'Provoke. Divination.',
    attack: 2,
    health: 4,
    keywords: ['provoke', 'divination'],
  },
  {
    id: 's-radiant-smite',
    name: 'Radiant Smite',
    cost: 3,
    type: 'ritual',
    rarity: 'common',
    pathway: 'sun',
    description: 'Deal 3 damage. Restore 3 Health to your hero.',
    effect: { type: 'damage', value: 3, target: 'any' },
  },
  {
    id: 's-paladin-squire',
    name: 'Paladin Squire',
    cost: 3,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'sun',
    description: '',
    attack: 3,
    health: 4,
  },

  // ─── 4-Cost ────────────────────────────────────────────────────────────
  {
    id: 's-divine-judgement',
    name: 'Divine Judgement',
    cost: 4,
    type: 'ritual',
    rarity: 'rare',
    pathway: 'sun',
    description: 'Deal 4 damage to a minion. Restore 4 Health to your hero.',
    effect: { type: 'damage', value: 4, target: 'enemy' },
  },
  {
    id: 's-holy-crusader',
    name: 'Holy Crusader',
    cost: 4,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'sun',
    description: 'Provoke',
    attack: 3,
    health: 6,
    keywords: ['provoke'],
  },
  {
    id: 's-blessed-warhammer',
    name: 'Blessed Warhammer',
    cost: 4,
    type: 'sealed-artifact',
    rarity: 'rare',
    pathway: 'sun',
    description: '',
    attack: 3,
    durability: 3,
  },
  {
    id: 's-consecration',
    name: 'Consecration',
    cost: 4,
    type: 'ritual',
    rarity: 'rare',
    pathway: 'sun',
    description: 'Deal 2 damage to all enemies.',
    effect: { type: 'damage', value: 2, target: 'all-enemies' },
  },

  // ─── 5-Cost ────────────────────────────────────────────────────────────
  {
    id: 's-light-of-creation',
    name: 'Light of Creation',
    cost: 5,
    type: 'ritual',
    rarity: 'epic',
    pathway: 'sun',
    description: 'Restore 8 Health to your hero.',
    effect: { type: 'heal', value: 8, target: 'friendly-hero' },
  },
  {
    id: 's-guardian-angel',
    name: 'Guardian Angel',
    cost: 5,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'sun',
    description: 'Provoke. Divination.',
    attack: 4,
    health: 6,
    keywords: ['provoke', 'divination'],
  },
  {
    id: 's-holy-word-shield',
    name: 'Holy Word: Shield',
    cost: 5,
    type: 'ritual',
    rarity: 'rare',
    pathway: 'sun',
    description: 'Give a minion +2/+4 and Divination.',
    effect: { type: 'buff', target: 'friendly', buffAttack: 2, buffHealth: 4 },
  },

  // ─── 6-Cost ────────────────────────────────────────────────────────────
  {
    id: 's-blazing-archangel',
    name: 'Blazing Archangel',
    cost: 6,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'sun',
    description: 'Provoke. Divination.',
    attack: 5,
    health: 7,
    keywords: ['provoke', 'divination'],
  },

  // ─── 7-Cost ────────────────────────────────────────────────────────────
  {
    id: 's-divine-radiance',
    name: 'Divine Radiance',
    cost: 7,
    type: 'ritual',
    rarity: 'epic',
    pathway: 'sun',
    description: 'Give all friendly minions +2/+2 and Divination.',
    effect: { type: 'buff', target: 'all-friendlies', buffAttack: 2, buffHealth: 2 },
  },
  {
    id: 's-celestial-paladin',
    name: 'Celestial Paladin',
    cost: 7,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'sun',
    description: 'Provoke. Divination. Frenzy.',
    attack: 5,
    health: 8,
    keywords: ['provoke', 'divination', 'frenzy'],
  },

  // ─── 8+ Cost ───────────────────────────────────────────────────────────
  {
    id: 's-eternal-blazing-sun',
    name: 'The Eternal Blazing Sun',
    cost: 10,
    type: 'beyonder',
    rarity: 'legendary',
    pathway: 'sun',
    description: 'Provoke. Divination. Restore 10 Health to your hero when played.',
    attack: 8,
    health: 10,
    keywords: ['provoke', 'divination'],
    flavorText: 'Light that never fades, warmth that never ends.',
  },
  {
    id: 's-solar-purification',
    name: 'Solar Purification',
    cost: 8,
    type: 'ritual',
    rarity: 'legendary',
    pathway: 'sun',
    description: 'Destroy all minions. Restore 10 Health to your hero.',
    effect: { type: 'destroy', target: 'all' },
    flavorText: 'In His radiance, only purity remains.',
  },

  // ─── Mystical Items ────────────────────────────────────────────────────
  {
    id: 's-divine-protection',
    name: 'Divine Protection',
    cost: 2,
    type: 'mystical-item',
    rarity: 'rare',
    pathway: 'sun',
    description: 'When your hero is attacked, restore 4 Health to your hero.',
    trigger: 'on-hero-attacked',
    effect: { type: 'heal', value: 4, target: 'friendly-hero' },
  },
  {
    id: 's-sanctuary-ward',
    name: 'Sanctuary Ward',
    cost: 3,
    type: 'mystical-item',
    rarity: 'epic',
    pathway: 'sun',
    description: 'When a friendly minion dies, restore 3 Health to your hero.',
    trigger: 'on-minion-death',
    effect: { type: 'heal', value: 3, target: 'friendly-hero' },
  },
];
