import { Card } from '../types.js';

export const TYRANT_CARDS: Card[] = [
  // ─── 1-Cost ────────────────────────────────────────────────────────────
  {
    id: 't-stormcaller-initiate',
    name: 'Stormcaller Initiate',
    cost: 1,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'tyrant',
    description: '',
    attack: 1,
    health: 2,
  },
  {
    id: 't-gust-of-fury',
    name: 'Gust of Fury',
    cost: 1,
    type: 'ritual',
    rarity: 'common',
    pathway: 'tyrant',
    description: 'Give a minion +2 Attack this turn.',
    effect: { type: 'buff', target: 'friendly', buffAttack: 2, buffHealth: 0 },
  },
  {
    id: 't-wave-runner',
    name: 'Wave Runner',
    cost: 1,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'tyrant',
    description: '',
    attack: 2,
    health: 1,
  },
  {
    id: 't-static-shock',
    name: 'Static Shock',
    cost: 1,
    type: 'ritual',
    rarity: 'common',
    pathway: 'tyrant',
    description: 'Deal 1 damage to a minion.',
    effect: { type: 'damage', value: 1, target: 'enemy' },
  },

  // ─── 2-Cost ────────────────────────────────────────────────────────────
  {
    id: 't-sailor-of-the-deep',
    name: 'Sailor of the Deep',
    cost: 2,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'tyrant',
    description: '',
    attack: 3,
    health: 2,
  },
  {
    id: 't-thunder-herald',
    name: 'Thunder Herald',
    cost: 2,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'tyrant',
    description: 'Frenzy',
    attack: 2,
    health: 3,
    keywords: ['frenzy'],
  },
  {
    id: 't-tidebreaker',
    name: 'Tidebreaker',
    cost: 2,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'tyrant',
    description: '',
    attack: 2,
    health: 3,
  },
  {
    id: 't-sea-trident',
    name: 'Sea Trident',
    cost: 2,
    type: 'sealed-artifact',
    rarity: 'common',
    pathway: 'tyrant',
    description: '',
    attack: 2,
    durability: 2,
  },

  // ─── 3-Cost ────────────────────────────────────────────────────────────
  {
    id: 't-lightning-strike',
    name: 'Lightning Strike',
    cost: 3,
    type: 'ritual',
    rarity: 'common',
    pathway: 'tyrant',
    description: 'Deal 3 damage.',
    effect: { type: 'damage', value: 3, target: 'any' },
  },
  {
    id: 't-ocean-enforcer',
    name: 'Ocean Enforcer',
    cost: 3,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'tyrant',
    description: 'Provoke',
    attack: 2,
    health: 4,
    keywords: ['provoke'],
  },
  {
    id: 't-gale-warrior',
    name: 'Gale Warrior',
    cost: 3,
    type: 'beyonder',
    rarity: 'common',
    pathway: 'tyrant',
    description: 'Frenzy',
    attack: 3,
    health: 3,
    keywords: ['frenzy'],
  },
  {
    id: 't-tempest-blessing',
    name: 'Tempest Blessing',
    cost: 3,
    type: 'ritual',
    rarity: 'rare',
    pathway: 'tyrant',
    description: 'Give a minion +2/+2.',
    effect: { type: 'buff', target: 'friendly', buffAttack: 2, buffHealth: 2 },
  },

  // ─── 4-Cost ────────────────────────────────────────────────────────────
  {
    id: 't-hurricane-warrior',
    name: 'Hurricane Warrior',
    cost: 4,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'tyrant',
    description: 'Frenzy',
    attack: 4,
    health: 4,
    keywords: ['frenzy'],
  },
  {
    id: 't-tsunami-wave',
    name: 'Tsunami Wave',
    cost: 4,
    type: 'ritual',
    rarity: 'rare',
    pathway: 'tyrant',
    description: 'Deal 2 damage to all minions.',
    effect: { type: 'damage', value: 2, target: 'all' },
  },
  {
    id: 't-storm-captain',
    name: 'Storm Captain',
    cost: 4,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'tyrant',
    description: 'Provoke',
    attack: 3,
    health: 5,
    keywords: ['provoke'],
  },
  {
    id: 't-neptune-hammer',
    name: 'Neptune Hammer',
    cost: 4,
    type: 'sealed-artifact',
    rarity: 'epic',
    pathway: 'tyrant',
    description: '',
    attack: 4,
    durability: 2,
  },

  // ─── 5-Cost ────────────────────────────────────────────────────────────
  {
    id: 't-sea-king-champion',
    name: 'Sea King Champion',
    cost: 5,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'tyrant',
    description: 'Frenzy. Provoke.',
    attack: 5,
    health: 5,
    keywords: ['frenzy', 'provoke'],
  },
  {
    id: 't-chain-lightning',
    name: 'Chain Lightning',
    cost: 5,
    type: 'ritual',
    rarity: 'epic',
    pathway: 'tyrant',
    description: 'Deal 3 damage to all enemies.',
    effect: { type: 'damage', value: 3, target: 'all-enemies' },
  },
  {
    id: 't-ocean-warlord',
    name: 'Ocean Warlord',
    cost: 5,
    type: 'beyonder',
    rarity: 'rare',
    pathway: 'tyrant',
    description: 'Frenzy. Divination.',
    attack: 4,
    health: 5,
    keywords: ['frenzy', 'divination'],
  },

  // ─── 6-Cost ────────────────────────────────────────────────────────────
  {
    id: 't-storm-sovereign',
    name: 'Storm Sovereign',
    cost: 6,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'tyrant',
    description: 'Haste',
    attack: 6,
    health: 5,
    keywords: ['haste'],
  },
  {
    id: 't-maelstrom',
    name: 'Maelstrom',
    cost: 6,
    type: 'ritual',
    rarity: 'epic',
    pathway: 'tyrant',
    description: 'Deal 3 damage to all minions. Draw 2 cards.',
    effect: { type: 'damage', value: 3, target: 'all' },
  },

  // ─── 7-Cost ────────────────────────────────────────────────────────────
  {
    id: 't-calamity-of-the-seas',
    name: 'Calamity of the Seas',
    cost: 7,
    type: 'ritual',
    rarity: 'epic',
    pathway: 'tyrant',
    description: 'Deal 4 damage to all enemies. Draw 2 cards.',
    effect: { type: 'damage', value: 4, target: 'all-enemies' },
  },
  {
    id: 't-deep-kraken',
    name: 'Deep Sea Kraken',
    cost: 7,
    type: 'beyonder',
    rarity: 'epic',
    pathway: 'tyrant',
    description: 'Provoke. Frenzy.',
    attack: 6,
    health: 8,
    keywords: ['provoke', 'frenzy'],
  },

  // ─── 8+ Cost ───────────────────────────────────────────────────────────
  {
    id: 't-lord-of-storms-nast',
    name: 'Lord of Storms (Nast)',
    cost: 9,
    type: 'beyonder',
    rarity: 'legendary',
    pathway: 'tyrant',
    description: 'Haste. Deal 3 damage to all enemy minions when played.',
    attack: 8,
    health: 7,
    keywords: ['haste'],
    flavorText: 'The sea bows, the sky trembles.',
  },
  {
    id: 't-wrath-of-poseidon',
    name: 'Wrath of Poseidon',
    cost: 10,
    type: 'ritual',
    rarity: 'legendary',
    pathway: 'tyrant',
    description: 'Deal 6 damage to all enemies.',
    effect: { type: 'damage', value: 6, target: 'all-enemies' },
    flavorText: 'The ocean remembers every slight.',
  },

  // ─── Mystical Items ────────────────────────────────────────────────────
  {
    id: 't-storm-ward',
    name: 'Storm Ward',
    cost: 2,
    type: 'mystical-item',
    rarity: 'rare',
    pathway: 'tyrant',
    description: 'When your hero is attacked, deal 3 damage to the attacker.',
    trigger: 'on-hero-attacked',
    effect: { type: 'damage', value: 3, target: 'random-enemy' },
  },
  {
    id: 't-counter-current',
    name: 'Counter Current',
    cost: 3,
    type: 'mystical-item',
    rarity: 'epic',
    pathway: 'tyrant',
    description: 'When enemy casts a spell, deal 4 damage to the enemy hero.',
    trigger: 'on-spell-cast',
    effect: { type: 'damage', value: 4, target: 'enemy-hero' },
  },
];
